apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config  # Shared ConfigMap for all services
  namespace: development
data:
  ENV: "development"  # Environment setting
  DATABASE_URL: "postgresql+asyncpg://postgres:2985@users-db-dev:5432/users-db-dev"
  # Shared PostgreSQL connection string for all services
