apiVersion: v1
kind: Service
metadata:
  name: users-db-dev  # PostgreSQL service
  namespace: development
spec:
  selector:
    app: users-db
    environment: development
  type: NodePort  # Expose DB on a local port
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32000  # Access via localhost:32000
