apiVersion: v1
kind: Service
metadata:
  name: users-db-dev  # PostgreSQL service
  namespace: development
spec:
  type: ExternalName  # Allows redirection to external services
  externalName: host.docker.internal  # Points to your local machine (Mac/Windows)
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
