apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-dev
spec:
  selector:
    app: rabbitmq
    environment: development
  type: NodePort  # Expose for local access
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30672  # Expose AMQP for dev access
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672  # Expose Management UI
